package main

import (
	"archive/zip"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
)

type xlsxSharedString struct { Text string `xml:"t"`; Runs []struct{ Text string `xml:"t"` } `xml:"r"` }
type xlsxWorkbook struct { Sheets []struct { Name string `xml:"name,attr"`; RID string `xml:"id,attr"` } `xml:"sheets>sheet"` }
type xlsxRelationships struct { Items []struct { ID string `xml:"Id,attr"`; Target string `xml:"Target,attr"` } `xml:"Relationship"` }
type xlsxCell struct { Ref string `xml:"r,attr"`; Type string `xml:"t,attr"`; Value string `xml:"v"`; Inline struct { Text string `xml:"t"`; Runs []struct{ Text string `xml:"t"` } `xml:"r"` } `xml:"is"` }
type xlsxRow struct { Cells []xlsxCell `xml:"c"` }

func zipEntry(z *zip.ReadCloser, name string) (*zip.File, error) { name=strings.TrimPrefix(path.Clean("/"+name),"/"); for _,f:=range z.File { if f.Name==name { return f,nil } }; return nil,fmt.Errorf("XLSX_INVALID: missing %s",name) }
func readXMLZip[T any](z *zip.ReadCloser,name string,out *T) error { f,err:=zipEntry(z,name); if err!=nil{return err}; r,err:=f.Open(); if err!=nil{return err}; defer r.Close(); if err=xml.NewDecoder(r).Decode(out); err!=nil{return fmt.Errorf("XLSX_INVALID: %w",err)}; return nil }
func loadSharedStrings(z *zip.ReadCloser)([]string,error){ f,err:=zipEntry(z,"xl/sharedStrings.xml"); if err!=nil{return nil,nil}; r,err:=f.Open(); if err!=nil{return nil,err}; defer r.Close(); dec:=xml.NewDecoder(r); values:=make([]string,0); for { tok,err:=dec.Token(); if err==io.EOF{break}; if err!=nil{return nil,fmt.Errorf("XLSX_INVALID: %w",err)}; start,ok:=tok.(xml.StartElement); if !ok||start.Name.Local!="si"{continue}; var item xlsxSharedString; if err=dec.DecodeElement(&item,&start);err!=nil{return nil,fmt.Errorf("XLSX_INVALID: %w",err)}; text:=item.Text; for _,run:=range item.Runs{text+=run.Text}; values=append(values,text) }; return values,nil }
func firstWorksheetPath(z *zip.ReadCloser)(string,error){ var wb xlsxWorkbook; if err:=readXMLZip(z,"xl/workbook.xml",&wb);err!=nil{return "",err}; if len(wb.Sheets)==0{return "",errors.New("XLSX_NO_SHEETS")}; var rels xlsxRelationships; if err:=readXMLZip(z,"xl/_rels/workbook.xml.rels",&rels);err!=nil{return "",err}; for _,rel:=range rels.Items{ if rel.ID==wb.Sheets[0].RID{ target:=strings.TrimPrefix(rel.Target,"/"); if strings.HasPrefix(target,"xl/"){return target,nil}; return path.Clean("xl/"+target),nil } }; return "",errors.New("XLSX_INVALID: worksheet relationship not found") }
func xlsxColumnIndex(ref string) int { idx:=0; for i:=0;i<len(ref);i++{ c:=ref[i]; if c<'A'||c>'Z'{ if c>='a'&&c<='z'{c-=32}else{break} }; idx=idx*26+int(c-'A'+1) }; return idx-1 }
func xlsxCellText(cell xlsxCell,shared []string)(string,error){ switch cell.Type{case "s": i,err:=strconv.Atoi(strings.TrimSpace(cell.Value)); if err!=nil||i<0||i>=len(shared){return "",errors.New("XLSX_INVALID: bad shared string")}; return shared[i],nil; case "inlineStr": text:=cell.Inline.Text; for _,r:=range cell.Inline.Runs{text+=r.Text}; return text,nil; case "b": if cell.Value=="1"{return "true",nil}; if cell.Value=="0"{return "false",nil}; return cell.Value,nil; default:return cell.Value,nil} }
func walkXLSXRows(filename string,visit func([]string)error)error{ z,err:=zip.OpenReader(filename); if err!=nil{return fmt.Errorf("XLSX_INVALID: %w",err)}; defer z.Close(); shared,err:=loadSharedStrings(z);if err!=nil{return err}; sheetPath,err:=firstWorksheetPath(z);if err!=nil{return err}; f,err:=zipEntry(z,sheetPath);if err!=nil{return err}; r,err:=f.Open();if err!=nil{return err};defer r.Close(); dec:=xml.NewDecoder(r); for{ tok,err:=dec.Token();if err==io.EOF{break};if err!=nil{return fmt.Errorf("XLSX_INVALID: %w",err)};start,ok:=tok.(xml.StartElement);if !ok||start.Name.Local!="row"{continue};var xr xlsxRow;if err=dec.DecodeElement(&xr,&start);err!=nil{return fmt.Errorf("XLSX_INVALID: %w",err)};max:=-1;for _,c:=range xr.Cells{if i:=xlsxColumnIndex(c.Ref);i>max{max=i}};if max<0{if err=visit(nil);err!=nil{return err};continue};row:=make([]string,max+1);for _,c:=range xr.Cells{i:=xlsxColumnIndex(c.Ref);if i<0{continue};text,e:=xlsxCellText(c,shared);if e!=nil{return e};row[i]=text};if err=visit(row);err!=nil{return err} };return nil }
func convertXLSXToJSON(filename string,w io.Writer,settings ConvertSettings)(ConvertStats,error){var headers []string;stats:=ConvertStats{};firstData:=true;err:=walkXLSXRows(filename,func(row []string)error{if headers==nil{var err error;headers,err=normaliseHeaders(row);if err!=nil{return err};stats.Columns=len(headers);_,err=io.WriteString(w,"[\n");return err};if !firstData{if _,err:=io.WriteString(w,",\n");err!=nil{return err}};firstData=false;if _,err:=io.WriteString(w,"  {\n");err!=nil{return err};for i,header:=range headers{if i>0{if _,err:=io.WriteString(w,",\n");err!=nil{return err}};key:=strconv.Quote(header);if _,err:=fmt.Fprintf(w,"    %s: ",key);err!=nil{return err};var raw string;if i<len(row){raw=row[i]};if err:=writeJSONValue(w,inferValueWithSettings(raw,settings));err!=nil{return err}};if _,err:=io.WriteString(w,"\n  }");err!=nil{return err};stats.Rows++;return nil});if err!=nil{return stats,err};if headers==nil{return stats,errors.New("HEADER_READ_FAILED")};if stats.Rows==0{_,err=io.WriteString(w,"]\n")}else{_,err=io.WriteString(w,"\n]\n")};return stats,err }
func inspectXLSXInput(filename string)(*InputSummary,error){absolutePath,err:=filepath.Abs(filepath.Clean(filename));if err!=nil{return nil,fmt.Errorf("FILE_READ_FAILED: %w",err)};info,err:=os.Stat(absolutePath);if err!=nil||info.IsDir(){return nil,errors.New("FILE_READ_FAILED")};var headers []string;preview:=make([][]string,0,previewRows);err=walkXLSXRows(absolutePath,func(row []string)error{if headers==nil{var e error;headers,e=normaliseHeaders(row);return e};copyRow:=make([]string,len(headers));copy(copyRow,row);preview=append(preview,copyRow);if len(preview)>=previewRows{return errPreviewComplete};return nil});if err!=nil&&!errors.Is(err,errPreviewComplete){return nil,err};if len(headers)==0{return nil,errors.New("HEADER_READ_FAILED")};return &InputSummary{Path:absolutePath,Name:info.Name(),Size:info.Size(),Kind:"xlsx",Columns:len(headers),Headers:headers,Preview:preview},nil }
func convertXLSXFilePath(inputPath,outputPath string,settings ConvertSettings,emit func(Progress))(ConvertStats,int64,error){if sameFilePath(inputPath,outputPath){return ConvertStats{},0,errors.New("OUTPUT_EQUALS_INPUT")};info,err:=os.Stat(inputPath);if err!=nil||info.IsDir(){return ConvertStats{},0,errors.New("FILE_READ_FAILED")};outputPath,err=filepath.Abs(filepath.Clean(outputPath));if err!=nil{return ConvertStats{},0,fmt.Errorf("OUTPUT_CREATE_FAILED: %w",err)};if err=os.MkdirAll(filepath.Dir(outputPath),0o755);err!=nil{return ConvertStats{},0,fmt.Errorf("OUTPUT_CREATE_FAILED: %w",err)};tmp,err:=os.CreateTemp(filepath.Dir(outputPath),".xlsx-to-json-*.tmp");if err!=nil{return ConvertStats{},0,fmt.Errorf("OUTPUT_CREATE_FAILED: %w",err)};tmpPath:=tmp.Name();committed:=false;defer func(){_=tmp.Close();if !committed{_=os.Remove(tmpPath)}}();if emit!=nil{emit(Progress{Percent:0,Total:info.Size()})};stats,err:=convertXLSXToJSON(inputPath,tmp,settings);if err!=nil{return stats,0,err};if err=tmp.Sync();err!=nil{return stats,0,fmt.Errorf("OUTPUT_WRITE_FAILED: %w",err)};if err=tmp.Close();err!=nil{return stats,0,fmt.Errorf("OUTPUT_WRITE_FAILED: %w",err)};outInfo,err:=os.Stat(tmpPath);if err!=nil{return stats,0,fmt.Errorf("OUTPUT_WRITE_FAILED: %w",err)};if err=replaceOutputFile(tmpPath,outputPath);err!=nil{return stats,0,fmt.Errorf("OUTPUT_WRITE_FAILED: %w",err)};committed=true;if emit!=nil{emit(Progress{Percent:100,Bytes:info.Size(),Total:info.Size()})};return stats,outInfo.Size(),nil }
